"""empty message

Revision ID: 257dbe049b1a
Revises: 
Create Date: 2019-09-30 22:36:22.095526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257dbe049b1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=55), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('git',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.String(length=30), nullable=True),
    sa.Column('repo_url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('git')
    op.drop_table('contacts')
    # ### end Alembic commands ###
