"""empty message

Revision ID: ae1d185f39ca
Revises: 45c0fcec3d7b
Create Date: 2019-09-28 15:19:42.991107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1d185f39ca'
down_revision = '45c0fcec3d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.String(length=30), nullable=True),
    sa.Column('repo_url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('git')
    # ### end Alembic commands ###
